---
# Deployment of our keptn-weatherapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keptn-weatherapp
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: keptn-weatherapp
  replicas: 1
  template:
    metadata:
      labels:
        run: keptn-weatherapp
    spec:
      containers:
        - name: keptn-weatherapp
          image: simonesan/weatherapp:latest # Todo: Replace this with your image name
          ports:
            - containerPort: 4200
          env:
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.7.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-default
---
# Expose keptn-weatherapp via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: keptn-weatherapp
  namespace: keptn
  labels:
    run: keptn-weatherapp
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: keptn-weatherapp

