version: '3'
services:
  weather-service:
    # build: .
    image: simonesan/weatherapp
    ports: 
      - 4200:4200
    container_name: weather-app
    networks:
      - weather
  nginx:
    image: nginx
    container_name: webserver
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - weather
  
networks:
  weather: