--- 
apiVersion: v1
kind: Service
metadata: 
  name: svc-weatherapp
spec: 
  type: ClusterIP
  ports: 
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4200
  selector: 
    app: svc-weatherapp
