apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: api-keptn-ingress
  namespace: keptn
spec:
  rules:
  - host: 35.203.149.57.xip.io
    http:
      paths:
      - backend:
          serviceName: api-gateway-nginx
          servicePort: 80